### PR TITLE
Attempting to make gradles much less of an eyesore

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Renamed `aptoidepreferences` to `aptoide-preferences` (to match other folder names).
- Deleted redundant subfolder .gitignore files (already covered by the main .gitignore) and ProGuard files in library folders.
- Reformat gradles to abide by the indentation size (using an untracked .editorconfig with only "indent_size = 2")
- Added sources / changelogs for every dependency to make documentation and updating necessary code easier to access
- Grouped dependencies into an understandable format
- Cleaned up duplicate things
- Update Gradle wrapper to 4.6
- Update Kotlin 1.3.21 to 1.3.31
- Update dexcount-gradle-plugin 0.6.1 to 0.6.4
- Update gradle-bintray-plugin 1.7.3 to 1.8.4
- Update PayPal Sdk 2.15.0 to 2.15.3 (this plugin is now deprecated)
- Update Chainfire's libsuperuser 1.0.0.+ to 1.1.0.201903290044
- Update MaterialTabStrip 1.1.0 to 1.1.1
- Update Espresso 3.0.1 to 3.0.2, and Runner/Rules 1.0.1 to 1.0.2

### CODE REVIEW

**Comment by apkbuilder-lw** [comment]
Can one of the admins verify this patch?

**Comment by TacoTheDank** [comment]
It would be good to have this reviewed ASAP to prevent having to deal with merge conflict headaches.

**Comment by jdandrade** [comment]
@TacoTheDank I hope you understand that this many updates to the gradle tasks dependencies take a while to test and to measure the impact. While we agree that those changes are in the right direction, it is very easy to a simple dependency update to break the app in runtime - you have dozens of them. This pull-request will be considered during the next 2w, so as soon as we consider it stable in QA and the code is reviewed we will let you know. I will ask you to resolve conflicts meanwhile, which they shouldn't be that many since we do not touch gradle tasks as often.

**Comment by TacoTheDank** [comment]
Ok. Thank you.

**Comment by TacoTheDank** [comment]
If you feel like leaving some things out (like some version updates), you can always cherry-pick the changes you do want :)

**Comment by TacoTheDank** [comment]
I'll revert the version changes and just leave the other stuff

**Pull request closed without merging**
