### PR TITLE
update gradles and dependencies

### PR DESCRIPTION
**Pull request by TacoTheDank**
Signed-off-by: TacoTheDank <SkytkRSfan3895@gmail.com>

**What does this PR do?**

   A few sentences describing the overall goals of the pull request's commits. 
To clean up the build.gradle files and make them more consistent with each other

   Explain any technical decisions that were made and why (when it makes sense).
added // where dependencies have updates that might potentially have breaking changes

### CODE REVIEW

**Comment by jdandrade** [comment]
Apk continues not do build, are you using Android studio, if yes, which version?
Please before opening another pull request, check if apk builds in the follower configuration:

build variants:
app - vanillaProdDebug
aptoide-account-manager - prodDebug
aptoide-analytics-core - debug
aptoide-analytics-default-implementation - debug
aptoide-database - debug
aptoidepreferences - debug
crashreports - debug
dataprovider - prodDebug
downloadmanager - debug
utils - debug

**Comment by TacoTheDank** [comment]
well geez this was a month ago lmao, i wouldve been using 3.1.4

ill resolve the conflicts

**Comment by jdandrade** [comment]
Not compiling, please open new pull request when code compiles.

**Comment by TacoTheDank** [comment]
I was going to close this anyway but forgot about it haha

**Pull request closed without merging**
