### PR TITLE
[AND-235] Fixes auto-scrolling

### PR DESCRIPTION
**Pull request by tomascarvalho7**
**What does this PR do?**

Fix auto scrolling.
Auto scrolling had an issue that it wouldn't scroll all the way to the bottom of the last message and would get increasingly worse the more messages were sent.

**Database changed?**

No

**Where should the reviewer start?**

- [ ] MessageList.kt

**How should this be manually tested?**

Send some messages to GameGenie and check if the scroll is behaving correctly.
  Flow on how to test this or QA Tickets related to this use-case: [AND-235](https://aptoide.atlassian.net/browse/AND-235)

**What are the relevant tickets?**

  Tickets related to this pull-request: [AND-235](https://aptoide.atlassian.net/browse/AND-235)

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

[AND-235]: https://aptoide.atlassian.net/browse/AND-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AND-235]: https://aptoide.atlassian.net/browse/AND-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by apkbuilder-lw** [comment]
Can one of the admins verify this patch?

**Comment by apkbuilder-lw** [comment]
Can one of the admins verify this patch?

**Review by phillipsgoncalves — COMMENTED** [review]
Missing confirmation in terms of design:
- new font
- color when writting should go from grey light to white also changes the font

**Comment by phillipsgoncalves** [comment]
Joao Andrade said to not implement the font change now.

**Pull request merged**
