### PR TITLE
Deprecation fixes

### PR DESCRIPTION
**Pull request by TacoTheDank**
**What does this PR do?**

 Fixes several non-Aptoide deprecations I had found laying around the project.

I think it's ok to change setBackgroundDrawable to setBackground, because the project's minSdk is 16 and setBackground was introduced in API 16.

I only made changes that I was positive wouldn't cause any breakages.

### CODE REVIEW

**Comment by apkbuilder-lw** [comment]
Can one of the admins verify this patch?

**Comment by phillipsgoncalves** [comment]
Hello, thank you for your contribution.

Could you please do the PR in dev instead of master ?
We only put code in master after it was released.

Thank you,
Filipe Gonçalves

**Comment by TacoTheDank** [comment]
@phillipsgoncalves Yep, sorry about that.

**Comment by phillipsgoncalves** [comment]
Hello,
could you please update your remote ? I am asking this because it looks like you are in a really old version, meaning that i can not even compile the project as the gradle version in your branch is still 2.3.3 while we are already using 3.6.1.
This will be helpful for future contributions as there will be less conflicts :) 

Thank you,
Filipe Gonçalves

**Comment by TacoTheDank** [comment]
@phillipsgoncalves I can't change the target branch of the pull request, so I just pulled dev into my fork's master. Should be good now.

**Comment by phillipsgoncalves** [comment]
Hello,
the app is crashing after opening it

Thank you, Filipe Gonçalves

**Comment by TacoTheDank** [comment]
@phillipsgoncalves Could you provide the crash log?

**Comment by phillipsgoncalves** [comment]
Why can't you build the app ? Building is really important to make sure that there are no errors caused by the changes done in the PR. For that reason, it is mandatory to run and build the project when you make a PR for the Aptoide repository.
Why can't you compile, is there a way that we can help you with it?

**Comment by TacoTheDank** [comment]
@phillipsgoncalves Sorry, I was just away from the computer for a while, so I couldn't build. I'm fine now.

**Comment by TacoTheDank** [comment]
I fixed the crash.

**Comment by TacoTheDank** [comment]
@phillipsgoncalves Any updates?

**Comment by phillipsgoncalves** [comment]
Hello, 
I am sorry for the delay, will look into it soon.
Thank you

**Review by Tigerkai31 — APPROVED** [review]

**Pull request closed without merging**
